### ISSUE TITLE
Plugin Repo Links Broken

### ISSUE THREAD

**Issue by mrjarbenne** [felixarntz/wp-encrypt#1]
Has the plugin been removed from the .org repo? The links on the description don't resolve. 

Thanks.

**Comment by felixarntz** [comment]
Hey, thanks for your interest in this plugin, but please don't use it yet. It is far from ready and will occasionally break. Once it is published though, I'd be happy if you check it out.

**Comment by mrjarbenne** [comment]
Thanks for the update, and for all the work so far. I saw the link to the repo and got excited that you had finished a version of it. I'll keep my excitement in check ;)
