### ISSUE TITLE
Issues in Creating Account

### ISSUE THREAD

**Issue by rizqinnazhif** [felixarntz/wp-encrypt#10]
This is the very first setting.
After inserting account data, and clicking [register account] button, I get this message in the dashboard.

**Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]**

Is the anything I can do ?

**Comment by felixarntz** [comment]
Thanks for letting me know! It looks like Let's Encrypt has updated their agreement. I will release a new version with a fix within the next hour.

**Comment by felixarntz** [comment]
Beta 4 is now available and should fix this problem. https://wordpress.org/plugins/wp-encrypt/
