### ISSUE TITLE
cURL error 3: malformed :(

### ISSUE THREAD

**Issue by anon4chan911** [felixarntz/wp-encrypt#11]
Здравствуйте! Спасибо вам за плагин, но даже с ним, к сожалению, у меня возникли трудности.

* Данная ошибка возникла после повторной генерации сертификата на WP Encrypt. 
* Стоит отметить, что ранее я деинсталлировал  WP Encrypt и удалял директорию ~/www/letsencrypt.
* Я уже выполнял сброс сертификатов и ключей по инструкции, которая была дана в FAQ в разделе "Something seems wrong and I would like to reset. How can I do that?": добавил в файл wp-config следующую запись define('WP_ENCRYPT_ENABLE_DANGER_ZONE', 'true') и после выполнил рестарт. (не помогло!)

Вы бы не могли мне помочь с данной проблемой? 
ps: извините, что не на английском.

**Comment by felixarntz** [comment]
This was fixed in Beta 6.
