### ISSUE TITLE
Godaddy shared hosting

### ISSUE THREAD

**Issue by rianbooyer** [felixarntz/wp-encrypt#12]
hey was wondering if it was possible to add a way to specify where the keys and certs were saved and what name they would be saved under. 
My situation is this on a godaddy shared hosting site i can get your plugin to work, you have it save to your directories on the server but it would be great if i could specify to save to godaddy's ssl directories instead (key, certs,etc) this way it automatically shows the renewal without having to move the files every 90 days since we don't have access to the virtual machine settings and the ssl redirect can't be put in a .htaccess file.

let me know what you think.

**Comment by felixarntz** [comment]
This is already possible by using a constant (see the [Plugin FAQ](https://wordpress.org/plugins/wp-encrypt/faq/) for instructions).

**Comment by rianbooyer** [comment]
o.k. could you give me an example of how to do this....also what about renaming the keys from something else besides .pem to .crt .key, etc that can be recognized by sites like godaddy is there a way to define a constant for that?

**Comment by R3dRidle** [comment]
Hey rianbooyer,

I had an issue like you and came up with a fix, perhaps this would help you?
https://github.com/felixarntz/wp-encrypt/issues/23
