### ISSUE TITLE
Nothing happens after Registration

### ISSUE THREAD

**Issue by nfstornado** [felixarntz/wp-encrypt#2]
After submitting the FTP-credentials in the register menu, nothing happens. I just get back to the settings screen. I don't even get the "Your account was registered on ..." message.
Currently i use a Multisite setting, but the same thing happens on my single site installation.

Additionally its worth to mention that i get the error that wordpress cant write in my directories, but it vanishes when i submit the FTP-credentials.

**Comment by felixarntz** [comment]
Hi Patrick, thanks for reporting this! I will look into it a little later this week.

**Comment by felixarntz** [comment]
I just fixed this bug, the fix will be included in the next version.
