### ISSUE TITLE
Wrong commonname?

### ISSUE THREAD

**Issue by R3dRidle** [felixarntz/wp-encrypt#24]
The plugin creates the certificate for www.domainname.ext and allso creates this directory in /letsencrypt/live

But at the hosting we use the most of the time it should be just domainname.ext without the www
Is this something that can be changed?

So in short, the commonname should be without www

By the way, this script DOES work but it's not a WP plugin.
https://github.com/analogic/lescript/blob/master/_example.php 

Some more info,

https://crt.sh/?id=40429931 this one is not made with the plugin but the script above.
https://crt.sh/?id=40871515 this one is made with the plugin.

As you can see the commonname in the subject is differtent.

**Comment by R3dRidle** [comment]
A possible fix for this would be to create a field in the backend for the common name (CN).

**Comment by Beheer80** [comment]
@R3dRidle  -> See #27 for the fix you need 👍

**Comment by felixarntz** [comment]
The www vs. non-www issue should be fixed through #42.
