### ISSUE TITLE
Challenge self check failed for domain xyz.de.

### ISSUE THREAD

**Issue by mightyx** [felixarntz/wp-encrypt#8]
When I click "Generate Certificate" I get "Challenge self check failed for domain xyz.de."
How do I find out whats wrong? What can I tell my hoster?

**Comment by felixarntz** [comment]
Hi! Please check this support ticket: https://wordpress.org/support/topic/challenge-self-check-failed-for-domain-nginx-problem

The issue you're describing sounds quite similar.
