### ISSUE TITLE
Invalid private key after directory change

### ISSUE THREAD

**Issue by nfstornado** [felixarntz/wp-encrypt#9]
Hey!
It would be nice if there would be somehow the option to choose the directery where the files should be generated. Right now they get generated 2 directories before my FTP-account has access. So i can't get the files

**Comment by felixarntz** [comment]
Hey!
You can completely customize the directory for the certificates and keys by using the `WP_ENCRYPT_SSL_CERTIFICATES_DIR_PATH` constant (define it in your `wp-config.php` and set it to the absolute path you would like the files to live at).

The directory for the HTTP challenges to verify domains with Let's Encrypt cannot be changed as it is `.well-known` inside the project root by convention.

Be aware that some configuration might be necessary to adjust the directory permissions to your need.

**Comment by nfstornado** [comment]
Oh now i remember that i already saw this in the plugin description, sorry!
But now i have another problem.
I defined the constant to /letsencrypt so that it uses my FTP root. And it created the `account` directory and the 2 .pem files. But now when i click on Generate Certificate i get the following error message:
`Invalid private key /letsencrypt/account/private.pem. Original error message: error:02001002:system library:fopen:No such file or directory`
But it is there, i can see it.

**Comment by felixarntz** [comment]
Have you tried resetting yet? When changing the location although you've used the plugin before, there might be issues. You can enable reset UI by putting the following line into your `wp-config.php`:

`define('WP_ENCRYPT_ENABLE_DANGER_ZONE', true);`

After that you should see a Reset button at the bottom of the WP Encrypt settings page. Click that to reset everything and then please try again. Let me know if the issue persists.

**Comment by felixarntz** [comment]
Closing because of lack of feedback, unable to recreate.
